default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bclog-development
  encoding: unicode
  username: dbuser
  password: dbuser

test:
  <<: *default
  database: bclog-test

production:
  <<: *default
  database: bclog-production
  encoding: unicode
  username: dbuser
  password: dbuser
