# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d400aeabce421670303d1085844f11a46cbedb9f2be73dae078bfaa45468f2907b27f958901eb86689dc7bcf430c7d49a937bfc939f7a1dbc408f9e824cf20e

test:
  secret_key_base: 7a54ab463dfccc4219fec84eb343767e6e735f6b334edd310640281075a02b6457818eba0684a987efdaff68e776d393ceb801496cb751ed0812795a8f40bfdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 28c71f34ef72855e825d204ff8d5aa4ca288ea55eb5aa631e6243581e0b4fb8bf9c55271d922580a3a10980d89dc4f7207713d0b83787bccbab9a4935f603a42